[package]
name = "heartrace"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
btleplug = "0.10"
crossterm = "0.24"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
anyhow = "1.0"
